

SELECT * 
FROM customer 
LIMIT 5;
--What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount)
from customer
group by gender;

--Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount
from customer
where discount_applied='Yes' 
and purchase_amount >=(select avg(purchase_amount)
from customer);

--What are the top 5 products with the highest average review rating?
select item_purchased,
avg(review_rating) as avg_review_rating
from customer
group by item_purchased
order by avg_review_rating desc
limit 5;

--Compare the average purchase amounts between Standard and Express Shipping.
SELECT
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS average_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express','Free Shipping')
GROUP BY shipping_type;

--Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
round(avg(purchase_amount),2) as average_spending,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status;

--Which 5 products have the highest percentage of purchases with discounts applied?
SELECT
    item_purchased,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;
--Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

select
case 
    when previous_purchases = 0 then 'new'
	when previous_purchases between 1 and 5 then 'returning'
	else 'loyal'
 end as customer_segment,
 count(*) as customer_count

from customer
group by customer_segment
order by customer_count desc;

--What are the top 3 most purchased products within each category?
SELECT
    category,
    item_purchased,
    COUNT(*) AS purchase_count
FROM customer
GROUP BY category, item_purchased;

--Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
    subscription_status,
    COUNT(*) AS customer_count
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;
--What is the revenue contribution of each age group?
SELECT
    CASE
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 45 THEN '36-45'
        WHEN age BETWEEN 46 AND 55 THEN '46-55'
        ELSE '56+'
    END AS age_group,
    SUM(purchase_amount) AS revenue_contribution
FROM customer
GROUP BY age_group
ORDER BY revenue_contribution DESC;
 